# Generated by Django 4.1.13 on 2024-10-20 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='default_username', max_length=40, unique=True, verbose_name='Usuario'),
        ),
    ]
