# Generated by Django 4.1.13 on 2024-11-03 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('imagen', models.CharField(max_length=100, verbose_name='Foto')),
                ('tipo', models.CharField(choices=[('Platillo', 'Platillo'), ('Bebida', 'Bebida')], max_length=50, verbose_name='Tipo')),
                ('existencia', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha creación')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'Menú',
                'verbose_name_plural': 'Menús',
            },
        ),
    ]
